### ISSUE TITLE
Bug Report On {SC-FEGAN}

### ISSUE THREAD

**Issue by Vito0924** [abtExp/arxivr#5]
Dear Author：

I could‘t find your implemention of SC-FEGAN, it seems a 404 error. Could you tell me how to find it? Thanks!

**Comment by abtExp** [comment]
Hi @Vito0924 , an untested rough implementation can be found [here](https://github.com/abtExp/arxivr/tree/master/arxivr/models/scfegan). But please keep in mind, this isn't the final implementation and as i mentioned in #4 , i'll be revamping the whole project real soon, as the framework of implementation is in progress, and it'll be up by next month, and the first paper that i'll be finishing will be SC-FEGAN. I lost track of this and several other projects as this has been a rough year. Stay tuned for major changes. Thanks for your interest in the project. You can follow other projects [here](https://github.com/explabs-ai)

**Comment by Vito0924** [comment]
> Hi @Vito0924 , an untested rough implementation can be found [here](https://github.com/abtExp/arxivr/tree/master/arxivr/models/scfegan). But please keep in mind, this isn't the final implementation and as i mentioned in #4 , i'll be revamping the whole project real soon, as the [framework](https://github.com/explabs-ai/projectaile) of implementation is in progress, and it'll be up by next month, and the first paper that i'll be finishing will be SC-FEGAN. I lost track of this and several other projects as this has been a rough year. Stay tuned for major changes. Thanks for your interest in the project. You can follow other projects [here](https://github.com/explabs-ai)
